name: Creative-Mojo
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Affordable Website and Social Media Solutions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010006'
    - '#363637'
    - '#b4b4b5'
    - '#747476'
    - '#e7e7e9'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
