name: Creative-Mojo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3723135555628687
title: Affordable Website and Social Media Solutions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010006'
    - '#363637'
    - '#b4b4b5'
    - '#747476'
    - '#e7e7e9'
  brandStrength: 0.6058318098075688
  lightness: 0.0316615616902709
  saturation: 0.7571909916587174
  rhythmicContrast: 0.0883316108956933
purpose: []
